spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://<--URL-->:3306/<--DB-->?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: *
    password: *

jwt:
  secret: TZ3w82PB7bLxrFgv4;GDS?d[hz.'<yUp

logging:
  level:
    jdbc.audit: OFF
    jdbc.connection: OFF
    jdbc.sql only: DEBUG
    jdbc.sql timing: INFO
    jdbc.result-settable: DEBUG
